package com.ecommerce.order_processing_system.domain;

public enum OrderStatus {
    PENDING,
    CREATED,
    PROCESSED,
    FAILED,
    PENDING_APPROVAL,
    FRAUD_DETECTED,
    WAREHOUSE_UNAVAILABLE,
    OUT_OF_STOCK,
    SUBSCRIPTION_LIMIT_EXCEEDED,
    DUPLICATE_ACTIVE_SUBSCRIPTION,
    INCOMPATIBLE_SUBSCRIPTIONS,
    ALREADY_OWNED,
    LICENSE_UNAVAILABLE,
    RELEASE_DATE_PASSED,
    CREDIT_LIMIT_EXCEEDED,
    PRE_ORDER_SOLD_OUT,
    INVALID_CORPORATE_DATA,
    INVALID_PAYMENT_TERMS
}
